# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20171127_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('quantity', models.IntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Album')),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
    ]
