# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20171130_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='album',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='album',
            field=models.IntegerField(default=1),
        ),
    ]
