# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20171130_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['Category'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
