# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20171130_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='WorM',
            field=models.BooleanField(default=True),
        ),
    ]
