# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20171203_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='album',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='price',
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.IntegerField(default=1),
        ),
    ]
