# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20171203_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Album'),
        ),
    ]
