# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0018_auto_20171203_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_list',
            options={'ordering': ['order_date'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
