# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0019_auto_20171203_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
